name: jelone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  google_fonts: ^5.1.0
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  firebase_crashlytics: ^3.3.5
  cloud_firestore: ^4.8.5
  font_awesome_flutter: ^10.5.0
  flutter_profile_picture: ^2.0.0
  url_launcher: ^6.2.6
  wechat_assets_picker: ^9.0.3
  file_picker: ^8.0.3
  native_video_player: ^1.3.1
  just_audio: ^0.9.38
  flutter_media_metadata: ^1.0.0
  uuid: ^4.4.0
  http: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Jelone.png" 
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/