// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb, kReleaseMode;
    
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
      );
    }
    if (kReleaseMode) {
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return androidR;
        case TargetPlatform.iOS:
          return iosR;
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
      } else {
        switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return androidD;
        case TargetPlatform.iOS:
          return iosD;
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }
  }

  static const FirebaseOptions androidD = FirebaseOptions(
    apiKey: 'AIzaSyABqHK7gIvn11ANqpf1ut9nASzVq6at_4o',
    appId: '1:371268598281:android:2f2a6faf9ae17a07b856d8',
    messagingSenderId: '371268598281',
    projectId: 'jelone-dev',
    storageBucket: 'jelone-dev.appspot.com',
  );

  static const FirebaseOptions iosD = FirebaseOptions(
    apiKey: 'AIzaSyDcgtDfyHHXrYLJFHH1EFu-Xne5AEMoAMM',
    appId: '1:371268598281:ios:b4c7c5cea15a7dbdb856d8',
    messagingSenderId: '371268598281',
    projectId: 'jelone-dev',
    storageBucket: 'jelone-dev.appspot.com',
    iosBundleId: 'site.ritom.jelone',
  );

      static const FirebaseOptions androidR = FirebaseOptions(
    apiKey: 'AIzaSyAeb1la67_OqDii3uhVQWQVvv42kmoUlt8',
    appId: '1:660206655354:android:b4cd6f7fcff99bbe2468c3',
    messagingSenderId: '660206655354',
    projectId: 'jelone-app',
    storageBucket: 'jelone-app.appspot.com',
  );

  static const FirebaseOptions iosR = FirebaseOptions(
    apiKey: 'AIzaSyASVRjSx3o-UJGHo7ke6q8hLW5ba2fAXHY',
    appId: '1:660206655354:ios:01ce5be04c0f3fc62468c3',
    messagingSenderId: '660206655354',
    projectId: 'jelone-app',
    storageBucket: 'jelone-app.appspot.com',
    iosBundleId: 'site.ritom.jelone',
  );

}